# Перейти в терминале в директорию addressIdentificator. Команда: cd addressIdentificator
# Написать команду mvn clean package
# Далее можно запустить данный файл

version: '3'

services:
  address-indentificator-server:
    build: ./
    container_name: address-indentificator-server
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
